### PR TITLE
_async renamed to async_ in betting endpoint

### PR DESCRIPTION
**Pull request by eugep**
#206

### CODE REVIEW

**Comment by liampauling** [comment]
Are you able to update the readme and examples as well?

**Comment by eugep** [comment]
I don't see any other occurrences of `_async` param used in `place_orders()` or  `replace_orders()` functions in the readme and examples. Do you intend to rename it in `start()`  function of `BetfairStream` ?

**Comment by liampauling** [comment]
Ah yes, would be good to be consistent throughout the library.

**Comment by eugep** [comment]
Ok, done!

**Pull request merged**
