### PR TITLE
Implement Available class in C

### PR DESCRIPTION
**Pull request by mberk**
This is a straight up port of the Available class to C with no attempts made to optimise the design.

I've tested that it produces an identical set of market books compared to the original Python code when reading one scraped Betfair prices file. It also (obviously) passes the tests.

I've used valgrind to check for any memory leaks or other incorrect object reference counting.

I still feel that the code would need to be tested much more comprehensively (i.e. on more price files across more machines) before it might be considered permanently replacing the Python implementation. An option could be that the user can choose whether to use this code at installation time e.g. `pip install betfairlightweight[c]`.

### CODE REVIEW

**Comment by synapticarbors** [comment]
From a maintainability perspective, I wonder if writing the C-extension with [Cython](https://cython.org/) would be better as it doesn't require knowledge of the Python C-API and will handle implementation changes needed for updates to CPython. I'm not sure if you take a small performance hit using Cython vs hand written C code calling the C-API, but it's minimal if my memory is correct.

**Comment by mberk** [comment]
@synapticarbors are you on the betfairlightweight Slack? Are you aware of the background of this PR?

**Comment by synapticarbors** [comment]
@mberk - I lurk over on the slack channel occasionally. I think you said that it was an experiment just to play around with the C-API, but correct me if I'm mistaken. I cloned your branch of this and tested it and didn't see any speed-up over the current pure python implementation, but I think in your testing you said there was a marginal speed-up. We may not be making the comparison in the same way. I'd be curious how you're benchmarking it.

 I threw together a cython example, which had nearly identical performance, and basically required just a few lines of code change (e.g. `cdef class Available` vs `class Available`). I think it's really hard to beat the current implementation just by switching to the C-API since you're still dealing with python objects, so the best you can hope for is a maybe cutting a small bit of overhead. Typically when I use cython and get 10-1000x speed ups, it's for pure number crunching where you're looping over hundreds or thousands of elements of numpy arrays, or working with C structs/arrays instead of python objects. The real trick to cython or any similar strategy (numba, wrapping C code using the C-API directly, etc), is to minimize how often you cross the boundary between python and the low level machine code (where you avoid accessing the python c-api) and try to stay on the latter's side as long as possible to avoid the function call overhead from swamping the gains.

**Comment by mberk** [comment]
@synapticarbors, yes this was partly a learning exercise but the hope was that it would be a drop-in replacement that offered a meaningful boost in speed.

My initial testing showed the code read historic data in 83% of the time as the baseline which I would describe as better than marginal but now that I've put together some more concrete results to show you I am getting the same as you: the code is about the same as the pure Python class. Like you, I am not at all surprised by this as the number of function calls and objects created is the same.

For reference, this is what I am now using to test the speed:

```python
import time

import betfairlightweight
from tqdm import tqdm
from tqdm import trange
from betfairlightweight import StreamListener

trading = betfairlightweight.APIClient("username", "password", "app_key")
listener = StreamListener(max_latency=None)
stream = trading.streaming.create_historical_generator_stream(
            file_path="/tmp/1.172557162",
                listener=listener,
                )
gen = stream.get_generator()
# Warmup
number_of_market_books = sum(1 for market_books in gen())
start_time = time.time()
for _ in trange(10):
    for market_books in tqdm(gen(), total=number_of_market_books):
        pass
print(time.time() - start_time)
```

I'm open to ideas from everyone on the best way to benchmark any potential performance improvements as I believe having a good, agreed-upon benchmark is an important starting point.

**Comment by synapticarbors** [comment]
Thanks for the concrete code. I was just running examples from the test suite using `timeit` (in a jupyter-lab notebook). So for example, things like:

```
current = [[27, 0.95], [13, 28.01], [1.02, 1157.21]]
%timeit available = Available(current, 1)
```

or 

```
book_update = [[30, 6.9], [1.01, 12]]
current = [[27, 0.95], [13, 28.01], [1.02, 1157.21]]
available = Available(current, 1)
%timeit available.update(book_update)
```

This was just to get at how much time creation of the object and updating the object took comparatively using each implementation (python, c-api, cython). Certainly this is a microbenchmark and repeatedly calling `update` on the same object with the same data isn't ideal, but I was just trying to get a feel for any stark differences (you can always call `%timeit -n1 -r1 available.update(book_update)` to call it once, which I also played around with). 

While I like your benchmark for trying to see if there is a change in real world performance on, I didn't have a good sense of how much time creation and updating the `Available` object took as a fraction of the whole workload, and whether it would be easy to detect small changes against the background of variability in all of the other functions that are being called. I think there's validity in doing these system level benchmarks as well as microbenchmarks of individual functionalities.

**Comment by mberk** [comment]
A fair comment that my benchmark is not isolating the code but my starting point was this comment from @liampauling on Slack:

> Having profiled (a lot) over the years I know the Available class is the bottleneck, contemplating a rewrite in C...

**Comment by liampauling** [comment]
Closing, refactor in 2.12 meets current demands.

**Pull request closed without merging**
